/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const mockLoader: typeof import('./mock/mockLoader')['default']
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface ComponentCustomProperties {
    readonly mockLoader: UnwrapRef<typeof import('./mock/mockLoader')['default']>
  }
}
